### ISSUE TITLE
no matches for kind "ClusterLogForwarder"

### ISSUE THREAD

**Issue by sushilHpal** [sabre1041/openshift-logforwarding-splunk#12]
At the time of exceuting below cmd, getting an error : **Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "ClusterLogForwarder" in version "logging.openshift.io/v1"**

helm upgrade -i --namespace=openshift-logging openshift-logforwarding-splunk charts/openshift-logforwarding-splunk/ --set forwarding.splunk.token=4a8a737d-5452-426c-a6f7-106dca4e813f

This is on OpenShift 4.6. Thanks!

**Comment by sabre1041** [comment]
@sushilHpal Did you install OpenShift logging before deploying?

**Comment by sushilHpal** [comment]
> @sushilHpal Did you install OpenShift logging before deploying?

great, I didn't expect a response so soon, thank you so much😊😜
