### ISSUE TITLE
some templates don't include namespace

### ISSUE THREAD

**Issue by mortya** [sabre1041/openshift-logforwarding-splunk#17]
Some of the templates don't set metadata.namespace.

This doesn't matter if you deploy directly with helm, because helm automatically sets the context to the namespace before applying the yaml.  But if you use **helm template** to generate yaml for deployment with some other tool, the generated yaml then gets deployed incorrectly.

**Comment by sabre1041** [comment]
@mortya Pushed https://github.com/sabre1041/openshift-logforwarding-splunk/commit/88bce81903d8b4f49a0be08eb68aa16d23a8d4a0 which should account for these concerns

**Comment by mortya** [comment]
Thank you!  Looking good.
