### ISSUE TITLE
Values.yaml file is missing

### ISSUE THREAD

**Issue by jettc** [sabre1041/openshift-logforwarding-splunk#22]
I have used this before and when I did a git clone, there was a openshift-logforwarding-splunk/charts/openshift-logforwarding-splunk/values.yaml file. Now even though the ReadME file references the values.yaml file, it does not exist in latest pull. Should I just copy old one over, or would it still work with latest version?

**Comment by sabre1041** [comment]
@jettc I pushed an update (15a83bc32f1db6e5b8ee0ca5cdecf347620c2433). It now correctly references the location of the chart and the associated values file

**Comment by sabre1041** [comment]
Closing as assets have been updated
