### ISSUE TITLE
Wrong helm path in log-forwarding-splunk-statefulset.yaml

### ISSUE THREAD

**Issue by lukyky414** [sabre1041/openshift-logforwarding-splunk#6]
`with .Values.nodeSelector` (l 135)
Should be
`with .Values.forwarding.fluentd.nodeSelector`

Same for `resources` (l 28), `affinity` (l 135), `tolerations` (l 143).

Helm does not work until:
```
sed -i '/Values\.forwarding\./! s:Values\.:Values.forwarding.fluentd.:' \
charts/openshift-logforwarding-splunk/templates/log-forwarding-splunk-statefulset.yaml
```

Did not check any other template, error found with "nodeSelector" not being applied.

**Comment by sabre1041** [comment]
Corrected via 74b00d9
