### ISSUE TITLE
Unable to get file status /etc/scl/conf/rh-ruby25: No such file or directory on newer RH-provided fluentd images

### ISSUE THREAD

**Issue by wtmthethird** [sabre1041/openshift-logforwarding-splunk#8]
This can likely be closed rather immediately as it is not an issue with the values in the current repo, but wanted to point out that 4.6 fluentd images are not including: `/etc/scl/conf/rh-ruby25`

so starting fluentd by `scl enable rh-ruby25 -- fluentd` will no longer function.

Thanks for all the work you do.

**Comment by sabre1041** [comment]
It appears scl has been removed in 4.6. I will do further testing, but you can probably delete the following lines

https://github.com/sabre1041/openshift-logforwarding-splunk/blob/master/charts/openshift-logforwarding-splunk/templates/log-forwarding-splunk-statefulset.yaml#L110-L113

**Comment by sabre1041** [comment]
@wtmthethird Updated to support 4.6 via 0af4145df6044c082f6c19bd1d3281c288b560ce

Can you retest?

**Comment by wtmthethird** [comment]
I can confirm that it works, and thank you!
